apiVersion: apps/v1
---
kind: Deployment
metadata:
  name: graduation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iti-frontend
      
  template:
    metadata:
      labels:
        app: iti-frontend
    spec:
      containers:
        - name: graduation
          image: engboda/iti_graduation
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: backend-service
         
